# Generated by Django 5.1.2 on 2025-06-01 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bolten', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='news_published_date',
            field=models.DateTimeField(null=True),
        ),
    ]
